pairs = [
    "AED/CNY OTC",
    "AUD/CAD",
    "AUD/CAD OTC",
    "AUD/CHF",
    "AUD/CHF OTC",
    "AUD/JPY",
    "AUD/JPY OTC",
    "AUD/NZD OTC",
    "AUD/USD",
    "AUD/USD OTC",
    "BHD/CNY OTC",
    "CAD/CHF",
    "CAD/CHF OTC",
    "CAD/JPY",
    "CAD/JPY OTC",
    "CHF/JPY",
    "CHF/JPY OTC",
    "CHF/NOK OTC",
    "EUR/AUD",
    "EUR/CAD",
    "EUR/CHF",
    "EUR/CHF OTC",
    "EUR/GBP",
    "EUR/HUF OTC",
    "EUR/JPY",
    "EUR/JPY OTC",
    "EUR/NZD OTC",
    "EUR/RUB OTC",
    "EUR/TRY OTC",
    "EUR/USD",
    "EUR/USD OTC",
    "GBP/AUD",
    "GBP/AUD OTC",
    "GBP/CAD",
    "GBP/CHF",
    "GBP/JPY",
    "GBP/JPY OTC",
    "GBP/USD",
    "GBP/USD OTC",
    "JOD/CNY OTC",
    "LBP/USD OTC",
    "TND/USD OTC",
    "USD/ARS OTC",
    "USD/BDT OTC",
    "USD/BRL OTC",
    "USD/CAD",
    "USD/CAD OTC",
    "USD/CHF",
    "USD/CHF OTC",
    "USD/CLP OTC",
    "USD/CNH OTC",
    "USD/COP OTC",
    "USD/DZD OTC",
    "USD/EGP OTC",
    "USD/IDR OTC",
    "USD/INR OTC",
    "USD/JPY",
    "USD/JPY OTC",
    "USD/MXN OTC",
    "USD/MYR OTC",
    "USD/PHP OTC",
    "USD/PKR OTC"
]